from flask import Flask, render_template, request, jsonify
from flask_cors import CORS
import os
from dotenv import load_dotenv
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_groq import ChatGroq
from langchain.prompts import PromptTemplate
import supabase
import hashlib

load_dotenv()

app = Flask(__name__)
CORS(app)

# Initialize Supabase
supabase_url = os.getenv("SUPABASE_URL")
supabase_key = os.getenv("SUPABASE_KEY")
supabase_client = supabase.create_client(supabase_url, supabase_key)

# Simple embedding function
def simple_embed(text: str) -> list:
    """Create a simple embedding from text using hash"""
    hash_obj = hashlib.sha256(text.encode())
    hash_bytes = hash_obj.digest()
    embedding = []
    for i in range(384):
        byte_val = hash_bytes[i % len(hash_bytes)]
        embedding.append((byte_val - 128) / 128.0)
    return embedding

# Initialize Groq LLM
llm = ChatGroq(
    model=os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile"),
    temperature=0.7,
    groq_api_key=os.getenv("GROQ_API_KEY")
)

# Create prompt
prompt_template = """Use the following pieces of context from President Biden's 2023 State of the Union address to answer the question. 
If you don't know the answer based on the context, say "I don't have information about that in the speech."

Context:
{context}

Question: {question}

Answer:"""

PROMPT = PromptTemplate(
    template=prompt_template,
    input_variables=["context", "question"]
)

def search_similar(query_embedding: list, k: int = 3):
    """Search for similar documents in Supabase"""
    try:
        response = supabase_client.rpc(
            "match_documents",
            {
                "query_embedding": query_embedding,
                "match_count": k,
                "match_threshold": 0.0
            }
        ).execute()
        return response.data if response.data else []
    except Exception as e:
        print(f"Error searching: {e}")
        return []

def store_embedding(content: str, embedding: list):
    """Store document chunk and embedding in Supabase"""
    try:
        response = supabase_client.table("documents").insert({
            "content": content,
            "embedding": embedding
        }).execute()
        return True
    except Exception as e:
        print(f"Error storing: {e}")
        return False

@app.route("/")
def index():
    return render_template("index.html")

@app.route("/api/chat", methods=["POST"])
def chat():
    try:
        data = request.json
        question = data.get("question", "").strip()
        
        if not question:
            return jsonify({"error": "Question cannot be empty"}), 400
        
        # Generate embedding for question
        question_embedding = simple_embed(question)
        
        # Search for similar documents
        results = search_similar(question_embedding, k=3)
        
        if not results:
            return jsonify({
                "answer": "I couldn't find relevant information in the speech.",
                "sources": []
            })
        
        # Prepare context
        context = "\n\n".join([result["content"] for result in results])
        
        # Generate answer
        prompt = PROMPT.format(context=context, question=question)
        answer = llm.predict(prompt)
        
        return jsonify({
            "answer": answer,
            "sources": [
                {
                    "text": result["content"][:300],
                    "similarity": result["similarity"]
                }
                for result in results
            ]
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route("/api/index", methods=["POST"])
def index_documents():
    try:
        print("Loading speech document...")
        
        # Get the directory where this script is located
        script_dir = os.path.dirname(os.path.abspath(__file__))
        speech_file = os.path.join(script_dir, "RAG-BidenSpeech/biden-sotu-2023-autogenerated-transcript.txt")
        
        if not os.path.exists(speech_file):
            return jsonify({"error": f"Speech file not found: {speech_file}"}), 400
        
        with open(speech_file, "r", encoding="utf-8") as f:
            text = f.read()
        
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200,
            separators=["\n\n", "\n", " ", ""]
        )
        chunks = text_splitter.split_text(text)
        
        print(f"Indexing {len(chunks)} chunks...")
        
        stored_count = 0
        for i, chunk in enumerate(chunks):
            embedding = simple_embed(chunk)
            if store_embedding(chunk, embedding):
                stored_count += 1
            
            if (i + 1) % 10 == 0:
                print(f"  Processed {i + 1}/{len(chunks)}")
        
        return jsonify({
            "status": "success",
            "message": f"Indexed {stored_count}/{len(chunks)} chunks successfully"
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    app.run(debug=True, port=5000)
