#!/usr/bin/env python3
"""
Production RAG Chatbot using Groq LLM, Sentence Transformers, and Supabase
"""

import os
from dotenv import load_dotenv
import supabase
from sentence_transformers import SentenceTransformer
from groq import Groq

load_dotenv()

# Initialize Supabase
supabase_url = os.getenv("SUPABASE_URL")
supabase_key = os.getenv("SUPABASE_KEY")
supabase_client = supabase.create_client(supabase_url, supabase_key)

# Initialize Groq client
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# Initialize embeddings model (lightweight, fast)
print("Loading embeddings model...")
embeddings_model = SentenceTransformer('all-MiniLM-L6-v2')

def embed_text(text: str) -> list:
    """Generate semantic embedding for text"""
    embedding = embeddings_model.encode(text, convert_to_tensor=False)
    return embedding.tolist()

def store_embedding(content: str, embedding: list):
    """Store document chunk and embedding in Supabase"""
    try:
        response = supabase_client.table("documents").insert({
            "content": content,
            "embedding": embedding
        }).execute()
        return True
    except Exception as e:
        print(f"Error storing: {e}")
        return False

def search_similar(query_embedding: list, k: int = 3):
    """Search for similar documents in Supabase"""
    try:
        response = supabase_client.rpc(
            "match_documents",
            {
                "query_embedding": query_embedding,
                "match_count": k,
                "match_threshold": 0.0
            }
        ).execute()
        return response.data if response.data else []
    except Exception as e:
        print(f"Error searching: {e}")
        return []

def load_and_index_documents():
    """Load speech and index it in Supabase"""
    print("\n📖 Loading speech document...")
    
    # Get the directory where this script is located
    script_dir = os.path.dirname(os.path.abspath(__file__))
    speech_file = os.path.join(script_dir, "RAG-BidenSpeech/biden-sotu-2023-autogenerated-transcript.txt")
    
    if not os.path.exists(speech_file):
        print(f"❌ Speech file not found: {speech_file}")
        return False
    
    with open(speech_file, "r", encoding="utf-8") as f:
        text = f.read()
    
    # Simple text splitting
    chunks = []
    current_chunk = ""
    for paragraph in text.split("\n\n"):
        if len(current_chunk) + len(paragraph) > 1000:
            if current_chunk:
                chunks.append(current_chunk)
            current_chunk = paragraph
        else:
            current_chunk += "\n\n" + paragraph if current_chunk else paragraph
    
    if current_chunk:
        chunks.append(current_chunk)
    
    print(f"✓ Created {len(chunks)} chunks from the speech")
    
    # Generate embeddings and store
    print("🔄 Generating embeddings and storing in Supabase...")
    
    stored_count = 0
    for i, chunk in enumerate(chunks):
        embedding = embed_text(chunk)
        if store_embedding(chunk, embedding):
            stored_count += 1
        
        if (i + 1) % 10 == 0:
            print(f"  Processed {i + 1}/{len(chunks)} chunks...")
    
    print(f"✓ Stored {stored_count}/{len(chunks)} chunks in Supabase")
    return True

def chat(question: str) -> dict:
    """Query the RAG chatbot"""
    try:
        # Generate embedding for question
        question_embedding = embed_text(question)
        
        # Search for similar documents
        results = search_similar(question_embedding, k=3)
        
        if not results:
            return {
                "answer": "I couldn't find relevant information in the speech.",
                "sources": []
            }
        
        # Prepare context from search results
        context = "\n\n".join([result["content"] for result in results])
        
        # Create prompt
        prompt = f"""Use the following pieces of context from President Biden's 2023 State of the Union address to answer the question. 
If you don't know the answer based on the context, say "I don't have information about that in the speech."

Context:
{context}

Question: {question}

Answer:"""
        
        # Generate answer using Groq
        message = groq_client.chat.completions.create(
            model=os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile"),
            max_tokens=1024,
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        
        answer = message.choices[0].message.content
        
        return {
            "answer": answer,
            "sources": [
                {
                    "text": result["content"][:200],
                    "similarity": result["similarity"]
                }
                for result in results
            ]
        }
    except Exception as e:
        return {
            "answer": f"Error: {str(e)}",
            "sources": []
        }

def interactive_chat():
    """Interactive chat mode"""
    print("\n" + "="*60)
    print("🤖 Biden Speech RAG Chatbot")
    print("="*60)
    print("Type 'quit' to exit\n")
    
    while True:
        question = input("You: ").strip()
        
        if question.lower() == "quit":
            print("Goodbye!")
            break
        
        if not question:
            continue
        
        print("\n🤔 Thinking...\n")
        response = chat(question)
        
        print(f"Bot: {response['answer']}\n")
        
        if response['sources']:
            print("📚 Sources:")
            for i, source in enumerate(response['sources'], 1):
                print(f"  {i}. {source['text']}... (similarity: {source['similarity']:.2f})\n")
        
        print("-" * 60 + "\n")

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == "index":
        load_and_index_documents()
    else:
        interactive_chat()
