#!/usr/bin/env python3
"""
Setup script for RAG-based Biden Speech Q&A System
Reads speech documents, generates embeddings using Google AI, and stores in Supabase
"""

import os
import sys
from dotenv import load_dotenv
import google.generativeai as genai
import supabase
from pathlib import Path

load_dotenv()

# Initialize Google AI
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
if not GOOGLE_API_KEY:
    print("❌ Error: GOOGLE_API_KEY not found in .env file")
    sys.exit(1)

genai.configure(api_key=GOOGLE_API_KEY)

# Initialize Supabase
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    print("❌ Error: SUPABASE_URL or SUPABASE_KEY not found in .env file")
    sys.exit(1)

supabase_client = supabase.create_client(SUPABASE_URL, SUPABASE_KEY)

def generate_embedding(text: str) -> list:
    """Generate embedding using Google AI Studio"""
    try:
        result = genai.embed_content(
            model="models/embedding-001",
            content=text,
            task_type="retrieval_document"
        )
        return result['embedding']
    except Exception as e:
        print(f"❌ Error generating embedding: {e}")
        return None

def load_speech_documents() -> str:
    """Load Biden speech documents"""
    print("\n📖 Loading Biden speech documents...")
    
    script_dir = Path(__file__).parent
    speech_files = [
        script_dir / "biden-sotu-2023-autogenerated-transcript.txt",
        script_dir / "biden-sotu-2023-planned-official.txt"
    ]
    
    combined_text = ""
    
    for speech_file in speech_files:
        if speech_file.exists():
            print(f"  ✓ Found: {speech_file.name}")
            with open(speech_file, "r", encoding="utf-8") as f:
                combined_text += f.read() + "\n\n"
        else:
            print(f"  ⚠ Not found: {speech_file.name}")
    
    if not combined_text:
        print("❌ No speech documents found!")
        sys.exit(1)
    
    return combined_text

def chunk_text(text: str, chunk_size: int = 1000, overlap: int = 200) -> list:
    """Split text into overlapping chunks"""
    print(f"\n✂️  Chunking text (size: {chunk_size}, overlap: {overlap})...")
    
    chunks = []
    start = 0
    
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end].strip()
        
        if chunk:
            chunks.append(chunk)
        
        start = end - overlap
    
    print(f"  ✓ Created {len(chunks)} chunks")
    return chunks

def store_in_supabase(chunks: list) -> int:
    """Store chunks and embeddings in Supabase"""
    print(f"\n💾 Storing {len(chunks)} chunks in Supabase...")
    
    # First, check if table exists and create if needed
    try:
        # Try to query the table
        supabase_client.table("biden_speech_chunks").select("id").limit(1).execute()
        print("  ✓ Table 'biden_speech_chunks' exists")
    except Exception as e:
        print(f"  ⚠ Table might not exist, attempting to create...")
        # The table should be created manually in Supabase with:
        # CREATE TABLE biden_speech_chunks (
        #   id BIGSERIAL PRIMARY KEY,
        #   content TEXT NOT NULL,
        #   embedding vector(768),
        #   created_at TIMESTAMP DEFAULT NOW()
        # );
        # CREATE INDEX ON biden_speech_chunks USING ivfflat (embedding vector_cosine_ops);
    
    stored_count = 0
    failed_count = 0
    
    for i, chunk in enumerate(chunks):
        try:
            # Generate embedding
            embedding = generate_embedding(chunk)
            
            if embedding is None:
                failed_count += 1
                continue
            
            # Store in Supabase
            response = supabase_client.table("biden_speech_chunks").insert({
                "content": chunk,
                "embedding": embedding
            }).execute()
            
            stored_count += 1
            
            if (i + 1) % 10 == 0:
                print(f"  ✓ Processed {i + 1}/{len(chunks)} chunks...")
        
        except Exception as e:
            print(f"  ❌ Error storing chunk {i}: {e}")
            failed_count += 1
    
    print(f"\n✅ Storage complete!")
    print(f"  ✓ Successfully stored: {stored_count} chunks")
    print(f"  ❌ Failed: {failed_count} chunks")
    
    return stored_count

def main():
    """Main setup function"""
    print("=" * 60)
    print("🇺🇸 RAG-based Biden Speech Q&A System - Setup")
    print("=" * 60)
    
    # Load documents
    speech_text = load_speech_documents()
    print(f"  Total text length: {len(speech_text):,} characters")
    
    # Chunk text
    chunks = chunk_text(speech_text)
    
    # Store in Supabase
    stored = store_in_supabase(chunks)
    
    if stored > 0:
        print("\n" + "=" * 60)
        print("✅ Setup completed successfully!")
        print("=" * 60)
        print("\nNext steps:")
        print("1. Ensure Supabase Edge Function 'biden-rag' is deployed")
        print("2. Visit: https://akhilchibber.github.io/RAG-BidenSpeech/")
        print("3. Start asking questions about Biden's speech!")
    else:
        print("\n❌ Setup failed - no chunks were stored")
        sys.exit(1)

if __name__ == "__main__":
    main()
